services:
  autoruby:
    image: ghcr.io/astral-sh/uv:0.8.0-python3.12-bookworm-slim
    volumes:
      - .:/workspace/autoruby
    working_dir: /workspace/autoruby
    environment:
      - UV_LINK_MODE=copy
      - UV_PROJECT_ENVIRONMENT=/usr/local
    entrypoint:
      - uv
      - run
      - --no-dev
      - python
      - autoruby.py
